---
ignition:
  version: 2.2.0
passwd:
  groups:
    - name: ssh
  users:
    - name: claudio
      sshAuthorizedKeys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCyvOm1lNZQDREfzZyTrR3rFXlqOkcg/gm0qj0Bohi/KSBNrY3Lb2b/7XtAGc6kp4DOYwvyH0I6GxAkQP6heA72OYd3T0sSK/RcMFQHW0DAVTV6CiRhCUV4fKwS57hnZ02sEP3on7gaCD5Mf8gm+zwSoLa+jgZ2MMQrwIz+BcE2rXrMXuPF4QAn9SHSpKA+ja8V/o89Dt4J58awWe3MsccpEnnvkyGoNb82h+Xl96OrCO1Kw5fiuk0LbOs5iVEnxu6rDcU0KFphE4Ggep/BtVPjSwYQDn3fAZ0z3TAUOisi7o+2tY8dq8+AuuvgsUnwpaiUQHpDlxurK5ZQ0/YFzxlVqq1Dm2rk1tuum7xhjimc5HbC5Jq+f7cB9C5MfC7I+uVfjS7PILqY+JEvayTr7C8tYEqD0hF/mmnePLMvTdnL6E5dpkkLKw9DjL3PGpn1KSlspGfY3GRkjzdiMUtrDDym42EflqJn3zAGlm8ZlA2INmOmUgeNr1JJTK2AjycqYIB/GVgG/J6kqf9HaFijGwuSxlyGq3OajKNgtL/WYhpK1O88FXV3rYi03CeG1kdQ3okigibuY+OnKsviUGlOwD+9BHnMnM1exfIYkpflAWI9GxGgFpM7RFuA3Mbag3KeJ0pM7zz+KBPeuSgubVpgpvRe3sIQQ6EWt77kgYk6Ma7C7w==
        claudio@net-sec.local
      groups:
      - sudo
      - docker
      - ssh
    - name: local-admin
      passwordHash: $6$jbwxN8UB$4op7Xz1BPV9SiSz8rkJJ6.zwgpWbe4/sqjs5duXy7e.3zUGh3MDyt11m62iFokkMMrFnYpWtlsJo1grf7XXfy.
      groups:
      - sudo
      - docker
storage:
  filesystems:
    - name: glusterfs
      mount:
        device: /dev/sdb1
        format: xfs
        wipe_filesystem: true
    - name: storageos
      mount:
        device: /dev/sdc1
        format: ext4
        wipe_filesystem: true
systemd:
  units:
    - name: docker.service
      enable: true
    - name: keepalived-mgmt.service
      enable: true
      contents:
        sourceFile: "files/etc/systemd/system/keepalived-mgmt.service"
    - name: keepalived-serv.service
      enable: true
      contents:
        sourceFile: "files/etc/systemd/system/keepalived-serv.service"
    - name: haproxy.service
      enable: true
      contents:
        sourceFile: "files/etc/systemd/system/haproxy.service"
    - name: gluster.mount
      enable: true
      contents:
        sourceFile: "files/etc/systemd/system/gluster.mount"
    - name: gluster.service
      enable: true
      contents:
        sourceFile: "files/etc/systemd/system/gluster.service"
    - name: bind.service
      enable: true
      contents:
        sourceFile: "files/etc/systemd/system/bind.service"
    - name: var-lib-storageos.mount
      enable: true
      contents:
        sourceFile: "files/etc/systemd/system/var-lib-storageos.mount"